version: "3.9"
services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_USER: postgres
      POSTGRESQL_HOST: db
    # command: ./bin/dev
    # tty: true
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRESQL_USER: postgres
volumes:
  postgres:

